name: luna_calendar
description: "Moon calendar"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Assets
  cupertino_icons: ^1.0.8

  # Multi lang
  intl: ^0.19.0
  intl_utils: ^2.8.11

  # State management
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0

  # Tools
  equatable: ^2.0.8

  # Local db
  shared_preferences: ^2.5.3

  # Router
  go_router: ^16.1.0

  # Animation
  animations: ^2.0.11
  get_storage: ^2.1.1
  introduction_screen: ^4.0.0
  gap: ^3.0.1

  # Intro

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
flutter_intl:
  enabled: true

  localizely:
    project_id: 16b6a255-5ddd-4e63-b688-923a5dbcaf65
